weights: yolov5s.pt
cfg: ''
data: "C:\\\u9773\u96E8\u6850\u7684\u5DE5\u4F5C\\\u4E0B\u8F7D\u7684\u4EE3\u7801\\\
  yolov5\\data\\polarity.yaml"
hyp: data\hyps\hyp.scratch-low.yaml
epochs: 300
batch_size: 16
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs\train
name: exp_polarity
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs\train\exp_polarity
